/**
 * PowerDNS Authoritative HTTP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.13
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 4.2.1.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * ConfigApi.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_API_ConfigApi_H_
#define ORG_OPENAPITOOLS_CLIENT_API_ConfigApi_H_


#include "../ApiClient.h"

#include "ConfigSetting.h"
#include <cpprest/details/basic_types.h>


#include <boost/optional.hpp>

namespace org {
namespace openapitools {
namespace client {
namespace api {

using namespace org::openapitools::client::model;



class  ConfigApi 
{
public:

    explicit ConfigApi( std::shared_ptr<ApiClient> apiClient );

    virtual ~ConfigApi();

    /// <summary>
    /// Returns all ConfigSettings for a single server
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="serverId">The id of the server to retrieve</param>
    pplx::task<std::vector<std::shared_ptr<ConfigSetting>>> getConfig(
        utility::string_t serverId
    );
    /// <summary>
    /// Returns a specific ConfigSetting for a single server
    /// </summary>
    /// <remarks>
    /// NOT IMPLEMENTED
    /// </remarks>
    /// <param name="serverId">The id of the server to retrieve</param>
    /// <param name="configSettingName">The name of the setting to retrieve</param>
    pplx::task<std::shared_ptr<ConfigSetting>> getConfigSetting(
        utility::string_t serverId,
        utility::string_t configSettingName
    );

protected:
    std::shared_ptr<ApiClient> m_ApiClient;
};

}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_API_ConfigApi_H_ */

