/**
 * PowerDNS Authoritative HTTP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.13
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 4.2.1.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * SearchApi.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_API_SearchApi_H_
#define ORG_OPENAPITOOLS_CLIENT_API_SearchApi_H_


#include "../ApiClient.h"

#include "SearchResults.h"
#include <cpprest/details/basic_types.h>


#include <boost/optional.hpp>

namespace org {
namespace openapitools {
namespace client {
namespace api {

using namespace org::openapitools::client::model;



class  SearchApi 
{
public:

    explicit SearchApi( std::shared_ptr<ApiClient> apiClient );

    virtual ~SearchApi();

    /// <summary>
    /// Search the data inside PowerDNS
    /// </summary>
    /// <remarks>
    /// Search the data inside PowerDNS for search_term and return at most max_results. This includes zones, records and comments. The * character can be used in search_term as a wildcard character and the ? character can be used as a wildcard for a single character.
    /// </remarks>
    /// <param name="serverId">The id of the server to retrieve</param>
    /// <param name="q">The string to search for</param>
    /// <param name="max">Maximum number of entries to return</param>
    /// <param name="objectType">Type of data to search for, one of “all”, “zone”, “record”, “comment” (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<SearchResults>> searchData(
        utility::string_t serverId,
        utility::string_t q,
        int32_t max,
        boost::optional<utility::string_t> objectType
    );

protected:
    std::shared_ptr<ApiClient> m_ApiClient;
};

}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_API_SearchApi_H_ */

