FROM ubuntu:bionic as dist-base

ARG BUILDER_CACHE_BUSTER=
ARG APT_URL
RUN apt-get update && apt-get -y dist-upgrade

@INCLUDE Dockerfile.sdbusplus
@INCLUDE Dockerfile.libyang
@INCLUDE Dockerfile.sysrepo

# Here we build the real package
@INCLUDE Dockerfile.pdns-sysrepo

RUN mkdir /sdist
