FROM ubuntu:bionic as dist-base

ARG BUILDER_CACHE_BUSTER=
ARG APT_URL
RUN apt-get update && apt-get -y dist-upgrade

@INCLUDE Dockerfile.sdbusplus
@INCLUDE Dockerfile.libyang
@INCLUDE Dockerfile.sysrepo

FROM dist-base as pkg-base

COPY --from=sdbusplus-builder /dist/3rdparty /dist/3rdparty
COPY --from=libyang-builder /dist/3rdparty /dist/3rdparty
COPY --from=sysrepo-builder /dist/3rdparty /dist/3rdparty

RUN mkdir /sdist
