@INCLUDE Dockerfile.target.sdist

FROM debian:buster as dist-base

ARG BUILDER_CACHE_BUSTER=
ARG APT_URL
RUN apt-get update && apt-get -y dist-upgrade

# Here we build the real package
@INCLUDE Dockerfile.pdns-sysrepo
