/**
 * PowerDNS Authoritative HTTP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.13
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 4.2.1.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * CacheFlushResult.h
 *
 * The result of a cache-flush
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_CacheFlushResult_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_CacheFlushResult_H_


#include "../ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace org {
namespace openapitools {
namespace client {
namespace model {


/// <summary>
/// The result of a cache-flush
/// </summary>
class  CacheFlushResult
    : public ModelBase
{
public:
    CacheFlushResult();
    virtual ~CacheFlushResult();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// CacheFlushResult members

    /// <summary>
    /// Amount of entries flushed
    /// </summary>
    double getCount() const;
    bool countIsSet() const;
    void unsetCount();

    void setCount(double value);

    /// <summary>
    /// A message about the result like \&quot;Flushed cache\&quot;
    /// </summary>
    utility::string_t getResult() const;
    bool resultIsSet() const;
    void unsetResult();

    void setResult(const utility::string_t& value);


protected:
    double m_Count;
    bool m_CountIsSet;
    utility::string_t m_Result;
    bool m_ResultIsSet;
};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_CacheFlushResult_H_ */
