/**
 * PowerDNS Authoritative HTTP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.13
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 4.2.1.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "Error.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {




Error::Error()
{
    m_Error = utility::conversions::to_string_t("");
    m_ErrorsIsSet = false;
}

Error::~Error()
{
}

void Error::validate()
{
    // TODO: implement validation
}

web::json::value Error::toJson() const
{
    web::json::value val = web::json::value::object();

    val[utility::conversions::to_string_t("error")] = ModelBase::toJson(m_Error);
    {
        std::vector<web::json::value> jsonArray;
        for( auto& item : m_Errors )
        {
            jsonArray.push_back(ModelBase::toJson(item));
        }
        if(jsonArray.size() > 0)
        {
            val[utility::conversions::to_string_t("errors")] = web::json::value::array(jsonArray);
        }
    }

    return val;
}

void Error::fromJson(const web::json::value& val)
{
    setError(ModelBase::stringFromJson(val.at(utility::conversions::to_string_t("error"))));
    {
        m_Errors.clear();
        std::vector<web::json::value> jsonArray;
        if(val.has_field(utility::conversions::to_string_t("errors")))
        {
        for( auto& item : val.at(utility::conversions::to_string_t("errors")).as_array() )
        {
            m_Errors.push_back(ModelBase::stringFromJson(item));
        }
        }
    }
}

void Error::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("error"), m_Error));
    {
        std::vector<web::json::value> jsonArray;
        for( auto& item : m_Errors )
        {
            jsonArray.push_back(ModelBase::toJson(item));
        }
        
        if(jsonArray.size() > 0)
        {
            multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("errors"), web::json::value::array(jsonArray), utility::conversions::to_string_t("application/json")));
        }
    }
}

void Error::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    setError(ModelBase::stringFromHttpContent(multipart->getContent(utility::conversions::to_string_t("error"))));
    {
        m_Errors.clear();
        if(multipart->hasContent(utility::conversions::to_string_t("errors")))
        {

        web::json::value jsonArray = web::json::value::parse(ModelBase::stringFromHttpContent(multipart->getContent(utility::conversions::to_string_t("errors"))));
        for( auto& item : jsonArray.as_array() )
        {
            m_Errors.push_back(ModelBase::stringFromJson(item));
        }
        }
    }
}

utility::string_t Error::getError() const
{
    return m_Error;
}

void Error::setError(const utility::string_t& value)
{
    m_Error = value;
    
}

std::vector<utility::string_t>& Error::getErrors()
{
    return m_Errors;
}

void Error::setErrors(const std::vector<utility::string_t>& value)
{
    m_Errors = value;
    m_ErrorsIsSet = true;
}

bool Error::errorsIsSet() const
{
    return m_ErrorsIsSet;
}

void Error::unsetErrors()
{
    m_ErrorsIsSet = false;
}

}
}
}
}


