/**
 * PowerDNS Authoritative HTTP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.13
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 4.2.1.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Metadata.h
 *
 * Represents zone metadata
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_Metadata_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_Metadata_H_


#include "../ModelBase.h"

#include <cpprest/details/basic_types.h>
#include <vector>

namespace org {
namespace openapitools {
namespace client {
namespace model {


/// <summary>
/// Represents zone metadata
/// </summary>
class  Metadata
    : public ModelBase
{
public:
    Metadata();
    virtual ~Metadata();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// Metadata members

    /// <summary>
    /// Name of the metadata
    /// </summary>
    utility::string_t getKind() const;
    bool kindIsSet() const;
    void unsetKind();

    void setKind(const utility::string_t& value);

    /// <summary>
    /// Array with all values for this metadata kind.
    /// </summary>
    std::vector<utility::string_t>& getMetadata();
    bool metadataIsSet() const;
    void unsetMetadata();

    void setMetadata(const std::vector<utility::string_t>& value);


protected:
    utility::string_t m_Kind;
    bool m_KindIsSet;
    std::vector<utility::string_t> m_Metadata;
    bool m_MetadataIsSet;
};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_Metadata_H_ */
