/**
 * PowerDNS Authoritative HTTP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.13
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 4.2.1.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Record.h
 *
 * The RREntry object represents a single record.
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_Record_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_Record_H_


#include "../ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace org {
namespace openapitools {
namespace client {
namespace model {


/// <summary>
/// The RREntry object represents a single record.
/// </summary>
class  Record
    : public ModelBase
{
public:
    Record();
    virtual ~Record();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// Record members

    /// <summary>
    /// The content of this record
    /// </summary>
    utility::string_t getContent() const;
    
    void setContent(const utility::string_t& value);

    /// <summary>
    /// Whether or not this record is disabled. When unset, the record is not disabled
    /// </summary>
    bool isDisabled() const;
    bool disabledIsSet() const;
    void unsetDisabled();

    void setDisabled(bool value);

    /// <summary>
    /// If set to true, the server will find the matching reverse zone and create a PTR there. Existing PTR records are replaced. If no matching reverse Zone, an error is thrown. Only valid in client bodies, only valid for A and AAAA types. Not returned by the server. This feature is deprecated and will be removed in 4.3.0.
    /// </summary>
    bool isSetPtr() const;
    bool setPtrIsSet() const;
    void unsetSet_ptr();

    void setSetPtr(bool value);


protected:
    utility::string_t m_Content;
        bool m_Disabled;
    bool m_DisabledIsSet;
    bool m_Set_ptr;
    bool m_Set_ptrIsSet;
};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_Record_H_ */
