/**
 * PowerDNS Authoritative HTTP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.13
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 4.2.1.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "RingStatisticItem.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {




RingStatisticItem::RingStatisticItem()
{
    m_Name = utility::conversions::to_string_t("");
    m_NameIsSet = false;
    m_Type = utility::conversions::to_string_t("");
    m_TypeIsSet = false;
    m_Size = 0;
    m_SizeIsSet = false;
    m_ValueIsSet = false;
}

RingStatisticItem::~RingStatisticItem()
{
}

void RingStatisticItem::validate()
{
    // TODO: implement validation
}

web::json::value RingStatisticItem::toJson() const
{
    web::json::value val = web::json::value::object();

    if(m_NameIsSet)
    {
        val[utility::conversions::to_string_t("name")] = ModelBase::toJson(m_Name);
    }
    if(m_TypeIsSet)
    {
        val[utility::conversions::to_string_t("type")] = ModelBase::toJson(m_Type);
    }
    if(m_SizeIsSet)
    {
        val[utility::conversions::to_string_t("size")] = ModelBase::toJson(m_Size);
    }
    {
        std::vector<web::json::value> jsonArray;
        for( auto& item : m_Value )
        {
            jsonArray.push_back(ModelBase::toJson(item));
        }
        if(jsonArray.size() > 0)
        {
            val[utility::conversions::to_string_t("value")] = web::json::value::array(jsonArray);
        }
    }

    return val;
}

void RingStatisticItem::fromJson(const web::json::value& val)
{
    if(val.has_field(utility::conversions::to_string_t("name")))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t("name"));
        if(!fieldValue.is_null())
        {
            setName(ModelBase::stringFromJson(fieldValue));
        }
    }
    if(val.has_field(utility::conversions::to_string_t("type")))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t("type"));
        if(!fieldValue.is_null())
        {
            setType(ModelBase::stringFromJson(fieldValue));
        }
    }
    if(val.has_field(utility::conversions::to_string_t("size")))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t("size"));
        if(!fieldValue.is_null())
        {
            setSize(ModelBase::int32_tFromJson(fieldValue));
        }
    }
    {
        m_Value.clear();
        std::vector<web::json::value> jsonArray;
        if(val.has_field(utility::conversions::to_string_t("value")))
        {
        for( auto& item : val.at(utility::conversions::to_string_t("value")).as_array() )
        {
            if(item.is_null())
            {
                m_Value.push_back( std::shared_ptr<SimpleStatisticItem>(nullptr) );
            }
            else
            {
                std::shared_ptr<SimpleStatisticItem> newItem(new SimpleStatisticItem());
                newItem->fromJson(item);
                m_Value.push_back( newItem );
            }
        }
        }
    }
}

void RingStatisticItem::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    if(m_NameIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("name"), m_Name));
    }
    if(m_TypeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("type"), m_Type));
    }
    if(m_SizeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("size"), m_Size));
    }
    {
        std::vector<web::json::value> jsonArray;
        for( auto& item : m_Value )
        {
            jsonArray.push_back(ModelBase::toJson(item));
        }
        
        if(jsonArray.size() > 0)
        {
            multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("value"), web::json::value::array(jsonArray), utility::conversions::to_string_t("application/json")));
        }
    }
}

void RingStatisticItem::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    if(multipart->hasContent(utility::conversions::to_string_t("name")))
    {
        setName(ModelBase::stringFromHttpContent(multipart->getContent(utility::conversions::to_string_t("name"))));
    }
    if(multipart->hasContent(utility::conversions::to_string_t("type")))
    {
        setType(ModelBase::stringFromHttpContent(multipart->getContent(utility::conversions::to_string_t("type"))));
    }
    if(multipart->hasContent(utility::conversions::to_string_t("size")))
    {
        setSize(ModelBase::int32_tFromHttpContent(multipart->getContent(utility::conversions::to_string_t("size"))));
    }
    {
        m_Value.clear();
        if(multipart->hasContent(utility::conversions::to_string_t("value")))
        {

        web::json::value jsonArray = web::json::value::parse(ModelBase::stringFromHttpContent(multipart->getContent(utility::conversions::to_string_t("value"))));
        for( auto& item : jsonArray.as_array() )
        {
            if(item.is_null())
            {
                m_Value.push_back( std::shared_ptr<SimpleStatisticItem>(nullptr) );
            }
            else
            {
                std::shared_ptr<SimpleStatisticItem> newItem(new SimpleStatisticItem());
                newItem->fromJson(item);
                m_Value.push_back( newItem );
            }
        }
        }
    }
}

utility::string_t RingStatisticItem::getName() const
{
    return m_Name;
}

void RingStatisticItem::setName(const utility::string_t& value)
{
    m_Name = value;
    m_NameIsSet = true;
}

bool RingStatisticItem::nameIsSet() const
{
    return m_NameIsSet;
}

void RingStatisticItem::unsetName()
{
    m_NameIsSet = false;
}

utility::string_t RingStatisticItem::getType() const
{
    return m_Type;
}

void RingStatisticItem::setType(const utility::string_t& value)
{
    m_Type = value;
    m_TypeIsSet = true;
}

bool RingStatisticItem::typeIsSet() const
{
    return m_TypeIsSet;
}

void RingStatisticItem::unsetType()
{
    m_TypeIsSet = false;
}

int32_t RingStatisticItem::getSize() const
{
    return m_Size;
}

void RingStatisticItem::setSize(int32_t value)
{
    m_Size = value;
    m_SizeIsSet = true;
}

bool RingStatisticItem::sizeIsSet() const
{
    return m_SizeIsSet;
}

void RingStatisticItem::unsetSize()
{
    m_SizeIsSet = false;
}

std::vector<std::shared_ptr<SimpleStatisticItem>>& RingStatisticItem::getValue()
{
    return m_Value;
}

void RingStatisticItem::setValue(const std::vector<std::shared_ptr<SimpleStatisticItem>>& value)
{
    m_Value = value;
    m_ValueIsSet = true;
}

bool RingStatisticItem::valueIsSet() const
{
    return m_ValueIsSet;
}

void RingStatisticItem::unsetValue()
{
    m_ValueIsSet = false;
}

}
}
}
}


