/**
 * PowerDNS Authoritative HTTP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.13
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 4.2.1.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "SearchResultComment.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {




SearchResultComment::SearchResultComment()
{
    m_Content = utility::conversions::to_string_t("");
    m_ContentIsSet = false;
    m_Name = utility::conversions::to_string_t("");
    m_NameIsSet = false;
    m_Object_type = utility::conversions::to_string_t("");
    m_Object_typeIsSet = false;
    m_Zone_id = utility::conversions::to_string_t("");
    m_Zone_idIsSet = false;
    m_Zone = utility::conversions::to_string_t("");
    m_ZoneIsSet = false;
}

SearchResultComment::~SearchResultComment()
{
}

void SearchResultComment::validate()
{
    // TODO: implement validation
}

web::json::value SearchResultComment::toJson() const
{
    web::json::value val = web::json::value::object();

    if(m_ContentIsSet)
    {
        val[utility::conversions::to_string_t("content")] = ModelBase::toJson(m_Content);
    }
    if(m_NameIsSet)
    {
        val[utility::conversions::to_string_t("name")] = ModelBase::toJson(m_Name);
    }
    if(m_Object_typeIsSet)
    {
        val[utility::conversions::to_string_t("object_type")] = ModelBase::toJson(m_Object_type);
    }
    if(m_Zone_idIsSet)
    {
        val[utility::conversions::to_string_t("zone_id")] = ModelBase::toJson(m_Zone_id);
    }
    if(m_ZoneIsSet)
    {
        val[utility::conversions::to_string_t("zone")] = ModelBase::toJson(m_Zone);
    }

    return val;
}

void SearchResultComment::fromJson(const web::json::value& val)
{
    if(val.has_field(utility::conversions::to_string_t("content")))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t("content"));
        if(!fieldValue.is_null())
        {
            setContent(ModelBase::stringFromJson(fieldValue));
        }
    }
    if(val.has_field(utility::conversions::to_string_t("name")))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t("name"));
        if(!fieldValue.is_null())
        {
            setName(ModelBase::stringFromJson(fieldValue));
        }
    }
    if(val.has_field(utility::conversions::to_string_t("object_type")))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t("object_type"));
        if(!fieldValue.is_null())
        {
            setObjectType(ModelBase::stringFromJson(fieldValue));
        }
    }
    if(val.has_field(utility::conversions::to_string_t("zone_id")))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t("zone_id"));
        if(!fieldValue.is_null())
        {
            setZoneId(ModelBase::stringFromJson(fieldValue));
        }
    }
    if(val.has_field(utility::conversions::to_string_t("zone")))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t("zone"));
        if(!fieldValue.is_null())
        {
            setZone(ModelBase::stringFromJson(fieldValue));
        }
    }
}

void SearchResultComment::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    if(m_ContentIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("content"), m_Content));
    }
    if(m_NameIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("name"), m_Name));
    }
    if(m_Object_typeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("object_type"), m_Object_type));
    }
    if(m_Zone_idIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("zone_id"), m_Zone_id));
    }
    if(m_ZoneIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("zone"), m_Zone));
    }
}

void SearchResultComment::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    if(multipart->hasContent(utility::conversions::to_string_t("content")))
    {
        setContent(ModelBase::stringFromHttpContent(multipart->getContent(utility::conversions::to_string_t("content"))));
    }
    if(multipart->hasContent(utility::conversions::to_string_t("name")))
    {
        setName(ModelBase::stringFromHttpContent(multipart->getContent(utility::conversions::to_string_t("name"))));
    }
    if(multipart->hasContent(utility::conversions::to_string_t("object_type")))
    {
        setObjectType(ModelBase::stringFromHttpContent(multipart->getContent(utility::conversions::to_string_t("object_type"))));
    }
    if(multipart->hasContent(utility::conversions::to_string_t("zone_id")))
    {
        setZoneId(ModelBase::stringFromHttpContent(multipart->getContent(utility::conversions::to_string_t("zone_id"))));
    }
    if(multipart->hasContent(utility::conversions::to_string_t("zone")))
    {
        setZone(ModelBase::stringFromHttpContent(multipart->getContent(utility::conversions::to_string_t("zone"))));
    }
}

utility::string_t SearchResultComment::getContent() const
{
    return m_Content;
}

void SearchResultComment::setContent(const utility::string_t& value)
{
    m_Content = value;
    m_ContentIsSet = true;
}

bool SearchResultComment::contentIsSet() const
{
    return m_ContentIsSet;
}

void SearchResultComment::unsetContent()
{
    m_ContentIsSet = false;
}

utility::string_t SearchResultComment::getName() const
{
    return m_Name;
}

void SearchResultComment::setName(const utility::string_t& value)
{
    m_Name = value;
    m_NameIsSet = true;
}

bool SearchResultComment::nameIsSet() const
{
    return m_NameIsSet;
}

void SearchResultComment::unsetName()
{
    m_NameIsSet = false;
}

utility::string_t SearchResultComment::getObjectType() const
{
    return m_Object_type;
}

void SearchResultComment::setObjectType(const utility::string_t& value)
{
    m_Object_type = value;
    m_Object_typeIsSet = true;
}

bool SearchResultComment::objectTypeIsSet() const
{
    return m_Object_typeIsSet;
}

void SearchResultComment::unsetObject_type()
{
    m_Object_typeIsSet = false;
}

utility::string_t SearchResultComment::getZoneId() const
{
    return m_Zone_id;
}

void SearchResultComment::setZoneId(const utility::string_t& value)
{
    m_Zone_id = value;
    m_Zone_idIsSet = true;
}

bool SearchResultComment::zoneIdIsSet() const
{
    return m_Zone_idIsSet;
}

void SearchResultComment::unsetZone_id()
{
    m_Zone_idIsSet = false;
}

utility::string_t SearchResultComment::getZone() const
{
    return m_Zone;
}

void SearchResultComment::setZone(const utility::string_t& value)
{
    m_Zone = value;
    m_ZoneIsSet = true;
}

bool SearchResultComment::zoneIsSet() const
{
    return m_ZoneIsSet;
}

void SearchResultComment::unsetZone()
{
    m_ZoneIsSet = false;
}

}
}
}
}


