/**
 * PowerDNS Authoritative HTTP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.13
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 4.2.1.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * SearchResult.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_SearchResult_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_SearchResult_H_


#include "../ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace org {
namespace openapitools {
namespace client {
namespace model {


/// <summary>
/// 
/// </summary>
class  SearchResult
    : public ModelBase
{
public:
    SearchResult();
    virtual ~SearchResult();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// SearchResult members

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getContent() const;
    bool contentIsSet() const;
    void unsetContent();

    void setContent(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    bool isDisabled() const;
    bool disabledIsSet() const;
    void unsetDisabled();

    void setDisabled(bool value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getName() const;
    bool nameIsSet() const;
    void unsetName();

    void setName(const utility::string_t& value);

    /// <summary>
    /// set to one of \&quot;record, zone, comment\&quot;
    /// </summary>
    utility::string_t getObjectType() const;
    bool objectTypeIsSet() const;
    void unsetObject_type();

    void setObjectType(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getZoneId() const;
    bool zoneIdIsSet() const;
    void unsetZone_id();

    void setZoneId(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getZone() const;
    bool zoneIsSet() const;
    void unsetZone();

    void setZone(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getType() const;
    bool typeIsSet() const;
    void unsetType();

    void setType(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    int32_t getTtl() const;
    bool ttlIsSet() const;
    void unsetTtl();

    void setTtl(int32_t value);


protected:
    utility::string_t m_Content;
    bool m_ContentIsSet;
    bool m_Disabled;
    bool m_DisabledIsSet;
    utility::string_t m_Name;
    bool m_NameIsSet;
    utility::string_t m_Object_type;
    bool m_Object_typeIsSet;
    utility::string_t m_Zone_id;
    bool m_Zone_idIsSet;
    utility::string_t m_Zone;
    bool m_ZoneIsSet;
    utility::string_t m_Type;
    bool m_TypeIsSet;
    int32_t m_Ttl;
    bool m_TtlIsSet;
};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_SearchResult_H_ */
