/**
 * PowerDNS Authoritative HTTP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.13
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 4.2.1.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * SearchResultZone.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_SearchResultZone_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_SearchResultZone_H_


#include "../ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace org {
namespace openapitools {
namespace client {
namespace model {


/// <summary>
/// 
/// </summary>
class  SearchResultZone
    : public ModelBase
{
public:
    SearchResultZone();
    virtual ~SearchResultZone();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// SearchResultZone members

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getName() const;
    bool nameIsSet() const;
    void unsetName();

    void setName(const utility::string_t& value);

    /// <summary>
    /// set to \&quot;zone\&quot;
    /// </summary>
    utility::string_t getObjectType() const;
    bool objectTypeIsSet() const;
    void unsetObject_type();

    void setObjectType(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getZoneId() const;
    bool zoneIdIsSet() const;
    void unsetZone_id();

    void setZoneId(const utility::string_t& value);


protected:
    utility::string_t m_Name;
    bool m_NameIsSet;
    utility::string_t m_Object_type;
    bool m_Object_typeIsSet;
    utility::string_t m_Zone_id;
    bool m_Zone_idIsSet;
};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_SearchResultZone_H_ */
